### ISSUE TITLE
how to run on windows platform?

### ISSUE THREAD

**Issue by wodsoe** [99991/matting#1]
how to run on windows platform?
Thank you！

**Comment by 99991** [comment]
I'm working on windows support. Will be done in a few days.

**Comment by wodsoe** [comment]
Thank you!

**Comment by wodsoe** [comment]
Could you convert c code to python code?

**Comment by 99991** [comment]
Should work on windows now even if gcc is not installed. However, only the vcycle alpha matting method will work since all other methods require the C library for performance.

**Comment by wodsoe** [comment]
Good job!
